name: Build && run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install -y libjansson-dev libavro-dev
    - name: Run
      run: make
